### PR TITLE
Set proper stock_item_id when creating stock movement

### PR DESCRIPTION
**Pull request by aleksandarpetrushev**
The issue is that instead of sending the stock_item_id we send the variant_id from the select2 on the StockMovement#new page. This is not newly introduced, it just worked because for all variants have the same id as their stock items. Did not manage to do this in the Javascript where it should be done. Obviously this is not the best solution. We need to somehow modify the JS (https://github.com/spree/spree_backend/blob/main/app/assets/javascripts/spree/backend/stock_movement.js) for the select (https://github.com/spree/spree_backend/blob/9db2f22ebe46671163b2fd566f470d27726277fe/app/views/spree/admin/stock_movements/_form.html.erb#L8) to have the correct value (the id of the stock item of the variant we are selecting, instead of the variant's id).

### CODE REVIEW

**Review by damianlegawiec — CHANGES_REQUESTED** [review]
@aleksandarpetrushev we need to fix it on the JS side

**Comment by aleksandarpetrushev** [comment]
> @aleksandarpetrushev we need to fix it on the JS side

I am having real difficulty debugging that JS code. Can you give some advice on how to debug, example to place a debugger in the processResults method of the select2?

**Comment by MatthewKennedy** [comment]
Hi @aleksandarpetrushev,

If you replace:
https://github.com/spree/spree_backend/blob/9db2f22ebe46671163b2fd566f470d27726277fe/app/views/spree/admin/stock_movements/_form.html.erb#L8

with:
`<%= select_tag 'stock_movement[stock_item_id]', nil , class: 'd-block w-100', id: 'stock_movement_stock_item_id', :'data-stock-location-id' => params[:stock_location_id] %>`

Then the javascript you mentioned will get fired:
https://github.com/spree/spree_backend/blob/main/app/assets/javascripts/spree/backend/stock_movement.js

**Comment by damianlegawiec** [comment]
@MatthewKennedy please review this PR, thank you!

**Comment by MatthewKennedy** [comment]
Will do this now...

**Comment by MatthewKennedy** [comment]
Al looks good:

`Parameters: {"authenticity_token"=>"[FILTERED]", "stock_movement"=>{"quantity"=>"33", "stock_item_id"=>"213"}, "button"=>"", "stock_location_id"=>"1"}`

**Review by MatthewKennedy — APPROVED** [review]

**Pull request merged**
